name: greek_diwan_app
description: "تطبيق الديوان اليوناني - تطبيق شامل عن اليونان وثقافتها وتاريخها وسياحتها"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  http: ^1.1.0
  cached_network_image: ^3.3.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  provider: ^6.0.0
  url_launcher: ^6.2.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#0066cc"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
